### ISSUE TITLE
Please don't autostart

### ISSUE THREAD

**Issue by simesy** [amazeeio/docker-haproxy#7]
Forgive me if i've misunderstood the situation or I'm in the wrong repo, but whenever i restart docker I get amazee-haproxy binding 0.0.0.0. I feel like this is bad manners and often conflicts with other applications I'm running.

<img width="1701" alt="Screen Shot 2020-08-10 at 15 03 14" src="https://user-images.githubusercontent.com/188856/89753282-f6889400-db1a-11ea-981f-dfb03d4ed00e.png">

**Comment by tobybellwood** [comment]
ah - the issue isn't with haproxy itself, it's with Pygmy - when pygmy started the container in docker, it calls it with `--restart=always` - https://github.com/amazeeio/pygmy/blob/master/lib/pygmy/haproxy.rb#L19

This is discussed over in https://github.com/amazeeio/pygmy/issues/40

Given we're close to shuttering pygmy in favour of alternatives, we'll make suggestions there.

**Comment by simesy** [comment]
aha! thanks

**Comment by tobybellwood** [comment]
(to disable for this container (until it's next needed)

`docker update --restart=no $(docker ps -f "name=amazeeio-haproxy" -q)`
